// Regenerates js/routes.js (precomputed sea routes). Run: node pandemic/tools/gen-routes.js
const fs = require("fs");
const path = require("path");
const root = path.join(__dirname, "..");
globalThis.d3 = require(path.join(root, "lib/d3.min.js"));
globalThis.topojson = require(path.join(root, "lib/topojson-client.min.js"));
require(path.join(root, "js/data.js"));
require(path.join(root, "js/world.js"));
const read = (f) => JSON.parse(fs.readFileSync(path.join(root, f)));
const topo = read("data/countries-50m.json");
const land = read("data/land-110m.json");
const world = PW.buildWorld(topo, land, d3, topojson);
const routes = world.shipRoutes; // computed by buildWorld, since js/routes.js is not loaded here
fs.writeFileSync(
  path.join(root, "js/routes.js"),
  "/* Generated by tools/gen-routes.js — sea routes between SEAPORTS (by index). */\n" +
    "(function (root) {\n  root.PW = root.PW || {};\n  root.PW.SHIP_ROUTES = " +
    JSON.stringify(routes) +
    ";\n})(typeof window !== \"undefined\" ? window : globalThis);\n"
);
console.log("wrote js/routes.js for", routes.length, "ports");
